// These constants represent the RISC-V ELF and the image ID generated by risc0-build.
// The ELF is used for proving and the ID is used for verification.
use core::MerkleInput;
use methods::{GUEST_CODE_FOR_ZKP_ELF, GUEST_CODE_FOR_ZKP_ID};
use risc0_zkvm::{default_prover, ExecutorEnv};
use serde_json::Value;
use std::fs;

// 輔助函式：將 Hex 字串轉為 [u8; 32]
fn decode_hex_32(s: &str) -> [u8; 32] {
    let bytes = hex::decode(s.replace("0x", "")).expect("無效的 Hex 字串");
    let mut array = [0u8; 32];
    array.copy_from_slice(&bytes);
    array
}

fn main() {
    // Initialize tracing. In order to view logs, run `RUST_LOG=info cargo run`
    tracing_subscriber::fmt()
        .with_env_filter(tracing_subscriber::filter::EnvFilter::from_default_env())
        .init();

    // 1. read Merkle tree data from JSON file
    println!(
        "[-] Current working directory: {:?}",
        std::env::current_dir().unwrap()
    );
    let tree_json_str =
        fs::read_to_string("/Users/yuu/Documents/Projects/ZKP/sbom-risc0/sbom/flask_server/flask_server_tree_data.json")
            .expect("Can't find merkle_tree_data.json");
    let tree_data: Value = serde_json::from_str(&tree_json_str).expect("JSON parse fail!");

    let mut all_leaf_hashes: Vec<[u8; 32]> = tree_data["components"]
        .as_array()
        .unwrap()
        .iter()
        .map(|c| decode_hex_32(c["hash"].as_str().unwrap()))
        .collect();
    // println!("[-] 傳入 Guest 的葉子數量: {}", all_leaf_hashes.len());

    // 2. 自動 Padding 至最近的 2 的冪次方
    let real_leaf_count = all_leaf_hashes.len();

    let mut next_power_of_2 = 1;
    while next_power_of_2 < real_leaf_count {
        next_power_of_2 *= 2;
    }

    // 3. 執行 Padding
    // println!(
    //     "[-] 原始組件: {}, 自動補齊至: {}",
    //     real_leaf_count, next_power_of_2
    // );

    while all_leaf_hashes.len() < next_power_of_2 {
        all_leaf_hashes.push([0u8; 32]); // 補 32 bytes 的零
    }

    // 4. 格式轉換：準備送入 zkVM 的 Input
    let root = decode_hex_32(tree_data["merkleRoot"].as_str().unwrap());

    let my_input = MerkleInput {
        root,
        all_leaf_hashes,
    };

    println!("[-] Preparing SBOM's ZK Prove...");

    // 5. 啟動 RISC Zero 證明程序
    let env = ExecutorEnv::builder()
        .write(&my_input)
        .unwrap()
        .build()
        .unwrap();

    // Obtain the default prover.
    let prover = default_prover();

    // Proof information by proving the specified ELF binary.
    // This struct contains the receipt along with statistics about execution of the guest
    let prove_info = prover.prove(env, GUEST_CODE_FOR_ZKP_ELF).unwrap();
    let receipt = prove_info.receipt;

    receipt.verify(methods::GUEST_CODE_FOR_ZKP_ID).unwrap();

    println!(
        "[+] Verification success! SBOM indeed exists with Merkle Root {}.",
        tree_data["merkleRoot"]
    );

    // The receipt was verified at the end of proving, but the below code is an
    // example of how someone else could verify this receipt.
    // receipt.verify(GUEST_CODE_FOR_ZKP_ID).unwrap();
}
